// Di aplikasi nyata, data ini akan berasal dari database atau API
// Data ini menggabungkan data ringkas dari `data.ts` dengan detail tambahan
export const projectsData = {
    "1": {
      id: 1,
      title: "Aplikasi Smart Campus IoT",
      description:
        "Mengembangkan sistem IoT untuk monitoring fasilitas kampus dengan dashboard real-time dan notifikasi otomatis untuk maintenance.",
      fullDescription: `
        Proyek ini akan mengembangkan sistem monitoring fasilitas kampus yang komprehensif menggunakan teknologi IoT. 
        Sistem akan mencakup monitoring suhu ruangan, kelembaban, kualitas udara, konsumsi listrik, dan status peralatan.
        
        Fitur utama yang akan dikembangkan:
        • Dashboard real-time untuk monitoring semua sensor
        • Sistem notifikasi otomatis via email dan mobile app
        • Analisis prediktif untuk maintenance preventif
        • Integrasi dengan sistem informasi kampus yang ada
        • Mobile app untuk teknisi maintenance
        
        Target pengguna: Staff IT kampus, teknisi maintenance, dan manajemen fasilitas.
      `,
      recruiter: {
        name: "Ahmad Maulana",
        avatar: "https://img.freepik.com/free-psd/portrait-man-teenager-isolated_23-2151745771.jpg?semt=ais_hybrid&w=740",
        major: "Teknik Informatika",
        university: "ITB",
        year: "Semester 7",
        rating: 4.8,
        projects: 12,
        connections: 150,
        completedProjects: 8,
        bio: "Passionate about IoT and smart systems. Experienced in full-stack development with a focus on embedded systems.",
        skills: ["IoT", "React", "Node.js", "Python", "Arduino"],
        socialLinks: {
          github: "#",
          linkedin: "#",
          portfolio: "#",
        },
      },
      skills: ["React", "IoT", "Python", "Arduino", "Node.js", "MongoDB", "MQTT"],
      duration: "3 bulan",
      startDate: "1 Maret 2024",
      endDate: "31 Mei 2024",
      members: "2/5",
      currentMembers: [
        { name: "Ahmad Maulana", role: "Project Lead & Backend", avatar: "https://img.freepik.com/free-psd/portrait-man-teenager-isolated_23-2151745771.jpg?semt=ais_hybrid&w=740" },
        { name: "Siti Nurhaliza", role: "Frontend Developer", avatar: "https://mahasiswa.dinus.ac.id/images/foto/A/A11/2022/A11.2022.14148.jpg" },
      ],
      neededRoles: [
          { role: "Hardware Engineer", description: "Desain dan implementasi sensor IoT.", skills: ["Arduino", "Electronics"], count: 1 },
          { role: "Mobile Developer", description: "Mengembangkan aplikasi mobile monitoring.", skills: ["React Native", "Flutter"], count: 1 },
          { role: "Data Analyst", description: "Analisis data sensor dan implementasi ML.", skills: ["Python", "Machine Learning"], count: 1 },
      ],
      type: "Tugas Akhir",
      location: "Bandung",
      workType: "Hybrid (Online + Lab ITB)",
      posted: "2 hari yang lalu",
      image: "https://assets-a1.kompasiana.com/items/album/2023/11/14/img-2721-6552c2dbedff761aa670e123.png",
      views: 145,
      applicants: 23,
      budget: "Rp 2.000.000",
      deadline: "15 Feb 2024",
      status: "Recruiting",
      timeline: [
          { phase: "Planning & Research", status: "completed", description: "Riset teknologi dan perencanaan arsitektur." },
          { phase: "Hardware Setup", status: "in-progress", description: "Setup sensor dan testing konektivitas." },
          { phase: "Backend Development", status: "pending", description: "Pengembangan API dan database." },
          { phase: "Frontend Development", status: "pending", description: "Dashboard web dan mobile app." },
          { phase: "Integration & Testing", status: "pending", description: "Integrasi semua komponen dan testing." },
      ],
      requirements: [
          "Pengalaman dengan IoT development.", "Familiar dengan protokol MQTT dan REST API.",
          "Kemampuan problem-solving yang baik.", "Dapat bekerja dalam tim.",
          "Tersedia minimal 20 jam per minggu.", "Domisili Bandung atau sekitarnya.",
      ],
      benefits: [
          "Pengalaman hands-on dengan teknologi IoT.", "Mentoring dari dosen & expert.",
          "Sertifikat completion dari ITB.", "Networking dengan profesional IT.",
          "Portfolio project untuk karir.", "Akses ke lab dan equipment ITB.",
      ],
      tags: ["IoT", "Smart Campus", "Real-time", "Dashboard", "Sensors", "Automation"],
    },
    "2": {
      id: 2,
      title: "Kampanye Sosial Lingkungan",
      description: "Merancang kampanye kreatif untuk meningkatkan kesadaran lingkungan di kalangan mahasiswa dengan pendekatan multimedia dan storytelling.",
      fullDescription: `Proyek Lomba ini bertujuan untuk menciptakan kampanye sosial yang berdampak tinggi mengenai isu lingkungan. Tim akan bertanggung jawab dari ideation, produksi konten, hingga distribusi di media sosial.`,
      recruiter: {
          name: "Sari Rahayu",
          avatar: "https://mahasiswa.dinus.ac.id/images/foto/A/A11/2022/A11.2022.14148.jpg",
          major: "Desain Komunikasi Visual",
          university: "UDINUS",
          year: "Semester 5",
          rating: 4.9,
          projects: 8,
          connections: 200,
          completedProjects: 5,
          bio: "Creative thinker with a passion for social causes. Experienced in video production and social media marketing.",
          skills: ["Video Editing", "Marketing", "Adobe Premiere", "Design"],
          socialLinks: { github: "#", linkedin: "#", portfolio: "#" },
      },
      skills: ["Design", "Marketing", "Video Editing", "Social Media", "Adobe Creative", "Copywriting"],
      duration: "2 bulan",
      startDate: "10 Februari 2024",
      endDate: "10 April 2024",
      members: "4/6",
      currentMembers: [
          { name: "Sari Rahayu", role: "Team Lead & Content Strategist", avatar: "https://mahasiswa.dinus.ac.id/images/foto/A/A11/2022/A11.2022.14148.jpg" },
          { name: "Bambang Pamungkas", role: "Videographer", avatar: "/placeholder.svg" },
          { name: "Cindy Claudia", role: "Graphic Designer", avatar: "/placeholder.svg" },
          { name: "Eko Yulianto", role: "Social Media Manager", avatar: "/placeholder.svg" },
      ],
      neededRoles: [
          { role: "Copywriter", description: "Membuat narasi dan teks yang persuasif untuk kampanye.", skills: ["Creative Writing"], count: 1 },
          { role: "Motion Graphic Artist", description: "Membuat animasi dan grafis bergerak untuk video.", skills: ["After Effects"], count: 1 },
      ],
      type: "Lomba",
      location: "Bandung",
      workType: "Fully Remote",
      posted: "1 hari yang lalu",
      image: "https://relungindonesia.org/wp-content/uploads/2024/09/WhatsApp-Image-2024-03-05-at-16.24.27.jpg",
      views: 67,
      applicants: 12,
      budget: "Hadiah Lomba",
      deadline: "20 Feb 2024",
      status: "Recruiting",
      timeline: [
          { phase: "Ideation & Concept", status: "completed", description: "Brainstorming dan finalisasi konsep kampanye." },
          { phase: "Content Production", status: "in-progress", description: "Proses syuting video dan desain grafis." },
          { phase: "Post-Production", status: "pending", description: "Editing video, sound design, dan motion graphics." },
          { phase: "Campaign Launch", status: "pending", description: "Distribusi konten di platform media sosial." },
      ],
      requirements: ["Kreatif dan inovatif.", "Mampu bekerja dengan deadline yang ketat.", "Pengalaman di bidang terkait (desain/video/sosmed)."],
      benefits: ["Meningkatkan portofolio.", "Pengalaman kerja tim di lingkungan kompetitif.", "Peluang memenangkan hadiah utama."],
      tags: ["Social Campaign", "Environment", "Multimedia", "DKV"],
    },
    "3": {
      id: 3,
      title: "Riset AI untuk Kesehatan",
      description: "Penelitian pengembangan model AI untuk diagnosis dini penyakit berbasis data medis menggunakan deep learning dan computer vision.",
      fullDescription: `Ini adalah proyek riset di bawah bimbingan dosen untuk mengembangkan model Machine Learning yang dapat membantu diagnosis penyakit dari citra medis (misalnya, X-ray atau CT Scan).`,
      recruiter: {
          name: "Dr. Pratama",
          avatar: "https://mahasiswa.dinus.ac.id/images/foto/A/A11/2022/A11.2022.14148.jpg",
          major: "Dosen Peneliti",
          university: "UI",
          year: "Faculty",
          rating: 5.0,
          projects: 25,
          connections: 500,
          completedProjects: 20,
          bio: "Researcher in AI and Medical Imaging. Focused on applying deep learning to solve real-world health problems.",
          skills: ["Machine Learning", "Python", "TensorFlow", "Computer Vision"],
          socialLinks: { github: "#", linkedin: "#", portfolio: "#" },
      },
      skills: ["Machine Learning", "Python", "TensorFlow", "Research", "Data Science", "Computer Vision", "PyTorch"],
      duration: "6 bulan",
      startDate: "15 Maret 2024",
      endDate: "15 September 2024",
      members: "1/3",
      currentMembers: [
          { name: "Dr. Pratama", role: "Principal Investigator", avatar: "https://mahasiswa.dinus.ac.id/images/foto/A/A11/2022/A11.2022.14148.jpg" },
      ],
      neededRoles: [
          { role: "Research Assistant", description: "Membantu dalam pengumpulan data, pre-processing, dan training model.", skills: ["Python", "Pandas"], count: 2 },
      ],
      type: "Riset Dosen",
      location: "Jakarta",
      workType: "Hybrid",
      posted: "3 hari yang lalu",
      image: "https://itbrief.asia/uploads/story/2024/12/11/techday_26169f03bf0a929134f3.webp",
      views: 89,
      applicants: 15,
      budget: "Hibah Riset",
      deadline: "28 Feb 2024",
      status: "Recruiting",
      timeline: [
          { phase: "Literature Review", status: "in-progress", description: "Mengkaji penelitian-penelitian terkait." },
          { phase: "Data Collection", status: "pending", description: "Mengumpulkan dan menganotasi dataset citra medis." },
          { phase: "Model Development", status: "pending", description: "Merancang dan melatih model deep learning." },
          { phase: "Evaluation & Paper Writing", status: "pending", description: "Mengevaluasi hasil dan menulis publikasi ilmiah." },
      ],
      requirements: ["Mahasiswa tingkat akhir atau S2.", "Memiliki dasar yang kuat di Machine Learning.", "IPK di atas 3.5."],
      benefits: ["Peluang publikasi di jurnal ilmiah.", "Pengalaman riset mendalam.", "Surat rekomendasi dari dosen."],
      tags: ["AI", "Healthcare", "Deep Learning", "Riset"],
    },
    "4": {
      id: 4,
      title: "E-commerce Platform UMKM",
      description: "Membangun platform e-commerce khusus untuk UMKM dengan fitur inventory management, payment gateway, dan analytics dashboard.",
      fullDescription: `Proyek startup ini bertujuan memberdayakan UMKM lokal dengan menyediakan platform e-commerce yang mudah digunakan dan terjangkau. Fitur utama mencakup manajemen produk, proses checkout, integrasi pembayaran, dan dashboard analitik untuk pemilik toko.`,
      recruiter: {
          name: "Budi Santoso",
          avatar: "https://mahasiswa.dinus.ac.id/images/foto/A/A11/2022/A11.2022.14148.jpg",
          major: "Sistem Informasi",
          university: "UGM",
          year: "Alumni",
          rating: 4.7,
          projects: 15,
          connections: 180,
          completedProjects: 10,
          bio: "Full-stack web developer with a passion for building scalable applications for small businesses.",
          skills: ["Laravel", "Vue.js", "AWS", "MySQL", "Inertia.js"],
          socialLinks: { github: "#", linkedin: "#", portfolio: "#" },
      },
      skills: ["Laravel", "Vue.js", "MySQL", "Payment Gateway", "AWS", "TailwindCSS", "Inertia.js"],
      duration: "4 bulan",
      startDate: "20 Februari 2024",
      endDate: "20 Juni 2024",
      members: "3/5",
      currentMembers: [
          { name: "Budi Santoso", role: "Full-stack Developer", avatar: "https://mahasiswa.dinus.ac.id/images/foto/A/A11/2022/A11.2022.14148.jpg" },
          { name: "Rina Sari", role: "UI/UX Designer", avatar: "/placeholder.svg" },
          { name: "Joko Anwar", role: "Backend Developer", avatar: "/placeholder.svg" },
      ],
      neededRoles: [
          { role: "Frontend Developer", description: "Mengimplementasikan desain UI/UX ke dalam Vue.js.", skills: ["Vue.js", "TailwindCSS"], count: 1 },
          { role: "DevOps Engineer", description: "Mengelola deployment dan infrastruktur di AWS.", skills: ["AWS", "Docker", "CI/CD"], count: 1 },
      ],
      type: "Startup",
      location: "Yogyakarta",
      workType: "Remote Friendly",
      posted: "1 minggu yang lalu",
      image: "https://bankjombang.co.id/wp-content/uploads/2023/05/tokopedia-platform-e-commerce-yang-paling-dipercaya-umkm-indonesia-jombang-kita.jpg",
      views: 123,
      applicants: 20,
      budget: "Equity/Saham",
      deadline: "10 Mar 2024",
      status: "Recruiting",
      timeline: [
          { phase: "System Design & UX", status: "completed", description: "Merancang arsitektur dan wireframe aplikasi." },
          { phase: "Core Backend Dev", status: "in-progress", description: "Membangun fitur utama backend dengan Laravel." },
          { phase: "Frontend Dev", status: "pending", description: "Membangun antarmuka pengguna dengan Vue.js." },
          { phase: "Deployment & Testing", status: "pending", description: "Deploy ke AWS dan melakukan UAT." },
      ],
      requirements: ["Menguasai stack Laravel/Vue.js.", "Memahami konsep arsitektur microservices.", "Mandiri dan proaktif."],
      benefits: ["Menjadi bagian dari tim inti startup.", "Potensi mendapatkan saham (equity).", "Bekerja dengan teknologi modern."],
      tags: ["E-commerce", "UMKM", "Startup", "Laravel", "VueJS"],
    },
    "5": {
      id: 5,
      title: "Game Edukasi Matematika",
      description: "Mengembangkan game mobile edukatif untuk pembelajaran matematika tingkat SD dengan gamifikasi yang menarik dan sistem reward.",
      fullDescription: `Proyek Tugas Akhir ini akan menciptakan sebuah game mobile yang membuat belajar matematika menjadi menyenangkan bagi anak-anak. Game akan terdiri dari berbagai level, mini-game, dan sistem reward untuk memotivasi pemain.`,
      recruiter: {
          name: "Lisa Permata",
          avatar: "https://mahasiswa.dinus.ac.id/images/foto/A/A11/2022/A11.2022.14647.jpg",
          major: "Teknik Informatika",
          university: "ITS",
          year: "Semester 7",
          rating: 4.6,
          projects: 10,
          connections: 120,
          completedProjects: 6,
          bio: "Game developer enthusiast, focusing on educational games. Proficient in Unity and C#.",
          skills: ["Unity", "C#", "Game Design", "Blender"],
          socialLinks: { github: "#", linkedin: "#", portfolio: "#" },
      },
      skills: ["Unity", "C#", "Game Design", "UI/UX", "Mobile Dev", "Firebase"],
      duration: "5 bulan",
      startDate: "1 April 2024",
      endDate: "1 September 2024",
      members: "2/4",
      currentMembers: [
          { name: "Lisa Permata", role: "Game Programmer", avatar: "https://mahasiswa.dinus.ac.id/images/foto/A/A11/2022/A11.2022.14647.jpg" },
          { name: "Rudi Hartono", role: "Game Designer", avatar: "/placeholder.svg" },
      ],
      neededRoles: [
          { role: "2D Artist / Illustrator", description: "Membuat aset visual, karakter, dan environment untuk game.", skills: ["Illustration", "Photoshop"], count: 1 },
          { role: "UI/UX Designer", description: "Merancang antarmuka game yang intuitif dan menarik untuk anak-anak.", skills: ["Figma", "UI/UX"], count: 1 },
      ],
      type: "Tugas Akhir",
      location: "Surabaya",
      workType: "Hybrid",
      posted: "4 hari yang lalu",
      image: "https://cdnpro.eraspace.com/media/wysiwyg/artikel/Tahun_2024/April/Game_Matematika_1.jpg",
      views: 78,
      applicants: 11,
      budget: "N/A (Proyek TA)",
      deadline: "25 Feb 2024",
      status: "Recruiting",
      timeline: [
          { phase: "Game Design Document (GDD)", status: "completed", description: "Finalisasi konsep, gameplay, dan desain game." },
          { phase: "Asset Production", status: "in-progress", description: "Pembuatan aset visual dan audio." },
          { phase: "Core Gameplay Programming", status: "pending", description: "Implementasi mekanik utama game dengan Unity." },
          { phase: "Level Design & Polishing", status: "pending", description: "Membuat level-level, balancing, dan bug fixing." },
      ],
      requirements: ["Passion di bidang game development.", "Portfolio yang relevan (untuk artist/designer).", "Bisa bekerja sama dalam tim."],
      benefits: ["Membangun game dari nol hingga rilis.", "Portofolio yang solid di industri game.", "Mengasah skill kolaborasi dan manajemen proyek."],
      tags: ["GameDev", "Edukasi", "Unity", "Mobile Game"],
    },
    "6": {
      id: 6,
      title: "Sistem Manajemen Perpustakaan",
      description: "Digitalisasi sistem perpustakaan dengan fitur peminjaman online, katalog digital, notifikasi otomatis, dan integrasi RFID.",
      fullDescription: `Proyek mata kuliah ini bertujuan untuk memodernisasi sistem perpustakaan konvensional. Mahasiswa akan membangun aplikasi web lengkap yang mencakup fitur untuk anggota perpustakaan dan admin, termasuk integrasi dengan hardware RFID untuk peminjaman mandiri.`,
      recruiter: {
          name: "Andi Wijaya",
          avatar: "https://mahasiswa.dinus.ac.id/images/foto/A/A11/2022/A11.2022.14647.jpg",
          major: "Teknik Komputer",
          university: "UNHAS",
          year: "Semester 6",
          rating: 4.5,
          projects: 7,
          connections: 95,
          completedProjects: 4,
          bio: "Web developer with interest in combining software and hardware. Familiar with PHP ecosystem.",
          skills: ["PHP", "CodeIgniter", "MySQL", "Bootstrap"],
          socialLinks: { github: "#", linkedin: "#", portfolio: "#" },
      },
      skills: ["PHP", "CodeIgniter", "MySQL", "Bootstrap", "RFID", "JavaScript", "HTML/CSS"],
      duration: "3 bulan",
      startDate: "5 Maret 2024",
      endDate: "5 Juni 2024",
      members: "1/4",
      currentMembers: [
          { name: "Andi Wijaya", role: "Project Manager & Backend", avatar: "https://mahasiswa.dinus.ac.id/images/foto/A/A11/2022/A11.2022.14647.jpg" },
      ],
      neededRoles: [
          { role: "Frontend Developer", description: "Membangun antarmuka yang responsif dengan Bootstrap.", skills: ["Bootstrap", "JavaScript", "AJAX"], count: 1 },
          { role: "Backend Developer", description: "Membantu mengembangkan fitur-fitur di sisi server.", skills: ["PHP", "CodeIgniter", "MySQL"], count: 1 },
          { role: "Hardware Integration", description: "Mengintegrasikan RFID reader dengan aplikasi web.", skills: ["RFID", "Serial Communication"], count: 1 },
      ],
      type: "Kuliah",
      location: "Makassar",
      workType: "On-site (Kampus)",
      posted: "5 hari yang lalu",
      image: "https://i.ytimg.com/vi/qrlD3zlK418/maxresdefault.jpg",
      views: 56,
      applicants: 9,
      budget: "N/A (Proyek Kuliah)",
      deadline: "18 Feb 2024",
      status: "Recruiting",
      timeline: [
          { phase: "Analisis Kebutuhan", status: "in-progress", description: "Mengumpulkan requirement dan membuat ERD." },
          { phase: "Database & Backend Setup", status: "pending", description: "Setup database dan struktur dasar backend." },
          { phase: "Frontend Development", status: "pending", description: "Implementasi desain UI/UX." },
          { phase: "RFID Integration & Testing", status: "pending", description: "Menghubungkan hardware dan testing akhir." },
      ],
      requirements: ["Mengikuti mata kuliah yang sama.", "Komitmen untuk menyelesaikan proyek tepat waktu.", "Kemampuan dasar web development."],
      benefits: ["Mendapatkan nilai bagus untuk mata kuliah.", "Pengalaman praktis membangun sistem full-stack.", "Belajar integrasi hardware-software."],
      tags: ["Perpustakaan", "WebDev", "PHP", "RFID", "CodeIgniter"],
    },
  };