import Navbar from "@/components/layout/navbar"; // Sesuaikan path jika perlu
import { Inter } from "next/font/google";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

// export const metadata: Metadata = {
//     title: "Create Next App",
//     description: "Generated by create next app",
//   };
export default function MainLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
      <body className={`${inter.variable} font-sans antialiased`}>
        <Navbar />
        {children}
      </body>
    
  );
}